apiVersion: v1
kind: Service
metadata:
  name: staffsync-service
  namespace: staffsync
  labels:
    app.kubernetes.io/name: staffsync-api
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: staffsync-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
